# Generated by Django 5.2 on 2025-05-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='caption',
        ),
    ]
