# Generated by Django 5.2 on 2025-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.IntegerField(choices=[(1, 'Available'), (0, 'Not Available')], default=1),
        ),
    ]
