# Generated by Django 5.2.1 on 2025-05-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover',
            field=models.ImageField(default=1, upload_to='room_images/'),
            preserve_default=False,
        ),
    ]
