# Generated by Django 5.2.1 on 2025-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default=1, upload_to='hotel_images/'),
            preserve_default=False,
        ),
    ]
